const SB = window.supabase.createClient(window.DEAD_WAX_SUPABASE.url, window.DEAD_WAX_SUPABASE.anonKey);
let authMode='signin', session=null, records=[], collections=[], links=[], currentRecord=null;
const $=s=>document.querySelector(s); const $$=s=>Array.from(document.querySelectorAll(s));
function msg(el,text,cls=''){el.textContent=text;el.className='msg '+cls}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function recordKey(r){return `${r.artist||''}|||${r.album||''}`}
async function init(){bindAuth(); bindApp(); const {data}=await SB.auth.getSession(); session=data.session; renderShell(); if(session) await loadAll(); SB.auth.onAuthStateChange((_e,s)=>{session=s; renderShell(); if(s) loadAll();});}
function bindAuth(){ $('#tabSignIn').onclick=()=>setAuthMode('signin'); $('#tabSignUp').onclick=()=>setAuthMode('signup'); $('#authForm').onsubmit=handleAuth; }
function setAuthMode(m){authMode=m; $('#tabSignIn').classList.toggle('on',m==='signin'); $('#tabSignUp').classList.toggle('on',m==='signup'); $('#authSubmit').textContent=m==='signin'?'Sign in':'Create account'; msg($('#authMsg'),'');}
async function handleAuth(e){e.preventDefault(); const email=$('#authEmail').value.trim(), password=$('#authPassword').value; msg($('#authMsg'),authMode==='signin'?'Signing in...':'Creating account...'); const res=authMode==='signin'? await SB.auth.signInWithPassword({email,password}) : await SB.auth.signUp({email,password,options:{data:{display_name:email.split('@')[0]}}}); if(res.error){msg($('#authMsg'),res.error.message,'err');return} session=res.data.session; msg($('#authMsg'),'Done','ok'); renderShell(); await loadAll();}
function bindApp(){ $('#signOutBtn').onclick=async()=>{await SB.auth.signOut(); location.reload()}; ['searchInput','collectionFilter','genreFilter','reactionFilter','listenedFilter','doublesFilter','grailFilter'].forEach(id=>$('#'+id).addEventListener('input',render)); $('#addRecordBtn').onclick=()=>openEditor(); }
function renderShell(){ const on=!!session; $('#authShell').classList.toggle('hidden',on); $('#appShell').classList.toggle('hidden',!on); if(on) $('#userEmail').textContent=session.user.email; }
async function loadAll(){ $('#syncMsg').textContent='Loading...'; const uid=session.user.id; const [r,c,l]=await Promise.all([SB.from('records').select('*').order('artist'),SB.from('collections').select('*').order('name'),SB.from('record_collections').select('*')]); if(r.error||c.error||l.error){$('#syncMsg').textContent=(r.error||c.error||l.error).message;return} records=r.data||[]; collections=c.data||[]; links=l.data||[]; await ensureDefaultCollections(uid); buildFilters(); render(); $('#syncMsg').textContent='Synced';}
async function ensureDefaultCollections(uid){ if(collections.length) return; for(const name of ["Dad's Collection","Augmented Collection"]){const {data,error}=await SB.from('collections').insert({user_id:uid,name,locked:false,source_id:name.toLowerCase().replace(/[^a-z0-9]+/g,'-')}).select().single(); if(!error) collections.push(data);} }
function buildFilters(){ const cf=$('#collectionFilter'), current=cf.value; cf.innerHTML='<option value="">All collections</option>'+collections.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join(''); cf.value=current; const genres=[...new Set(records.flatMap(r=>[r.genre,...(Array.isArray(r.genres)?r.genres:[])].filter(Boolean)))].sort(); const gf=$('#genreFilter'), gv=gf.value; gf.innerHTML='<option value="">All genres</option>'+genres.map(g=>`<option>${esc(g)}</option>`).join(''); gf.value=gv; }
function recordCollectionIds(id){return links.filter(l=>l.record_id===id).map(l=>l.collection_id)}
function recordCollections(id){const ids=recordCollectionIds(id); return collections.filter(c=>ids.includes(c.id))}
function filtered(){ const q=$('#searchInput').value.toLowerCase().trim(), col=$('#collectionFilter').value, gen=$('#genreFilter').value, rea=$('#reactionFilter').value; return records.filter(r=>{ if(q&&!`${r.artist} ${r.album} ${r.shelf_id||''}`.toLowerCase().includes(q)) return false; if(col&&!recordCollectionIds(r.id).includes(col)) return false; if(gen&&!(r.genre===gen||(Array.isArray(r.genres)&&r.genres.includes(gen)))) return false; if(rea){ if(rea==='liked'&&!r.liked) return false; if(rea!=='liked'&&r.reaction!==rea) return false; } if($('#listenedFilter').checked&&!r.listened) return false; if($('#doublesFilter').checked&&!(Number(r.copies_owned)>1)) return false; if($('#grailFilter').checked&&!r.grail) return false; return true; });}
function render(){ const list=filtered(); $('#shownCount').textContent=list.length; $('#totalCount').textContent=records.length; $('#emptyState').classList.toggle('hidden',list.length); $('#grid').innerHTML=list.map(cardHtml).join(''); $$('.card').forEach(el=>el.onclick=()=>openDetail(records.find(r=>r.id===el.dataset.id)));}
function cardHtml(r){return `<article class="card" data-id="${r.id}"><div class="cover">${r.cover_url?`<img src="${esc(r.cover_url)}" loading="lazy">`:'No cover'}${r.grail?'<span class="grail-dot">★</span>':''}</div><div class="card-body"><div class="artist">${esc(r.artist)}</div><div class="album">${esc(r.album)}</div><div class="meta"><span class="pill">${esc(r.shelf_id||'No ID')}</span>${Number(r.copies_owned)>1?`<span class="pill">${r.copies_owned} copies</span>`:''}${r.listened?'<span class="pill">Listened</span>':''}</div></div></article>`}
function openDetail(r){currentRecord=r; const cols=recordCollections(r.id).map(c=>c.name).join(', ')||'No collection'; $('#modal').className='modal'; $('#modal').innerHTML=`<div class="dialog ${r.grail?'grail':''}"><button type="button" class="close">×</button><div class="detail-top"><div class="detail-cover">${r.cover_url?`<img src="${esc(r.cover_url)}">`:'No cover'}</div><div class="detail-info"><div class="detail-code">${esc(r.shelf_id||'No Shelf ID')}</div><div class="artist">${esc(r.artist)}</div><div class="album">${esc(r.album)}</div><div class="status-row"><span class="pill">${esc(r.genre||'Unknown genre')}</span><span class="pill">${esc(cols)}</span>${r.listened?'<span class="pill">Listened</span>':''}${r.liked?'<span class="pill">Liked</span>':''}${r.grail?'<span class="pill">Grail record</span>':''}</div></div><div class="actions"><button type="button" class="btn danger" id="deleteBtn">Remove</button><button type="button" class="btn primary" id="editBtn">Edit Record</button></div></div><div class="detail-body"><h2 class="section-title">Tracks</h2><div class="tracks">${tracksHtml(r.tracklist)}</div></div></div>`; $('.close').onclick=closeModal; $('#editBtn').onclick=()=>openEditor(r); $('#deleteBtn').onclick=()=>deleteRecord(r);}
function tracksHtml(t){ if(!Array.isArray(t)||!t.length) return '<p class="notice">No tracklist stored.</p>'; return t.map(x=>`<div class="track"><strong>${esc(x.position||'')}</strong><span>${esc(x.title||'Untitled')}</span><em>${esc(x.duration||'')}</em></div>`).join('');}
function closeModal(){ $('#modal').className='modal hidden'; $('#modal').innerHTML=''; currentRecord=null;}
function openEditor(r=null){ const is=!!r; $('#modal').className='modal'; $('#modal').innerHTML=`<div class="dialog"><button type="button" class="close">×</button><div class="detail-body"><h2 class="section-title">${is?'Edit':'Add'} Record</h2><form id="recordForm" class="edit-grid"><div class="field"><label>Artist</label><input name="artist" required value="${esc(r?.artist||'')}"></div><div class="field"><label>Album</label><input name="album" required value="${esc(r?.album||'')}"></div><div class="field"><label>Shelf ID</label><input name="shelf_id" value="${esc(r?.shelf_id||'')}"></div><div class="field"><label>Copies Owned</label><input name="copies_owned" type="number" min="1" value="${esc(r?.copies_owned||1)}"></div><div class="field"><label>Genre</label><input name="genre" value="${esc(r?.genre||'')}"></div><div class="field"><label>Reaction</label><select name="reaction"><option value="">None</option><option value="liked">Liked</option><option value="neutral">Neutral</option><option value="disliked">Disliked</option></select></div><label class="check-wrap"><input name="listened" type="checkbox" ${r?.listened?'checked':''}>Listened</label><label class="check-wrap"><input name="liked" type="checkbox" ${r?.liked?'checked':''}>Liked</label><label class="check-wrap"><input name="grail" type="checkbox" ${r?.grail?'checked':''}>Grail Record</label><div class="field wide"><label>Cover URL</label><input name="cover_url" value="${esc(r?.cover_url||'')}"></div><div class="form-actions wide"><button type="button" class="btn" id="cancelEdit">Cancel</button><button type="submit" class="btn primary">Save</button></div></form></div></div>`; $('.close').onclick=closeModal; $('#cancelEdit').onclick=closeModal; if(r?.reaction) $('[name=reaction]').value=r.reaction; $('#recordForm').onsubmit=e=>saveRecord(e,r);}
async function saveRecord(e,old){e.preventDefault(); const f=new FormData(e.target); const uid=session.user.id; const payload={user_id:uid,artist:f.get('artist').trim(),album:f.get('album').trim(),shelf_id:f.get('shelf_id')||null,copies_owned:Number(f.get('copies_owned')||1),genre:f.get('genre')||null,reaction:f.get('reaction')||null,cover_url:f.get('cover_url')||null,listened:f.has('listened'),liked:f.has('liked'),grail:f.has('grail')}; const before=old?{...old}:null; let res= old? await SB.from('records').update(payload).eq('id',old.id).select().single() : await SB.from('records').insert(payload).select().single(); if(res.error){alert(res.error.message);return} await logChange(old?'update':'create',res.data.id,before,res.data); closeModal(); await loadAll(); openDetail(res.data);}
async function deleteRecord(r){ if(!confirm(`Remove ${r.artist} — ${r.album}?`)) return; const before={...r}; const {error}=await SB.from('records').delete().eq('id',r.id); if(error){alert(error.message);return} await logChange('delete',r.id,before,null); closeModal(); await loadAll();}
async function logChange(action,record_id,before_data,after_data){await SB.from('change_log').insert({user_id:session.user.id,record_id,action,before_data,after_data});}
init();
