const SB = window.supabase.createClient(window.DEAD_WAX_SUPABASE.url, window.DEAD_WAX_SUPABASE.anonKey);
const $=s=>document.querySelector(s); const log=t=>{$('#log').textContent=t}; const details=t=>{$('#details').textContent+=t+'\n'};
let session=null;
async function init(){const {data}=await SB.auth.getSession(); session=data.session; show(); $('#signin').onclick=signIn; $('#importBtn').onclick=importDb;}
function show(){const on=!!session; $('#authBox').classList.toggle('hidden',on); $('#importBox').classList.toggle('hidden',!on); if(on) $('#who').textContent=session.user.email;}
async function signIn(){log('Signing in...'); const {data,error}=await SB.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value}); if(error){log(error.message);return} session=data.session; log('Signed in.'); show();}
function parseDb(txt){const sandbox={window:{}}; Function('window',txt+'; return window.VINYL_ARCHIVE_DISCOGS_DB;')(sandbox.window); return sandbox.window.VINYL_ARCHIVE_DISCOGS_DB;}
function normCollectionName(name){return name||'Imported Collection'}
async function ensureCollections(db){const uid=session.user.id; const map=new Map(); const source=(db.user&&db.user.collections)||[]; for(const c of source){const name=normCollectionName(c.name); let {data,error}=await SB.from('collections').upsert({user_id:uid,name,locked:!!c.locked,source_id:c.id},{onConflict:'user_id,name'}).select().single(); if(error) throw error; map.set(c.id,data.id); map.set(name,data.id);} return map;}
function entryToRecord(key,e,uid){const [artist,album]=key.split('|||'); const raw=e||{}; return {user_id:uid,artist:artist||'Unknown Artist',album:album||'Unknown Album',shelf_id:raw.code||raw.shelfId||raw.shelf_id||null,copies_owned:Math.max(1,Number(raw.owned||raw.copiesOwned||raw.copies_owned||1)),grail:!!raw.grail,listened:!!raw.listened,liked:!!raw.liked,reaction:raw.reaction||raw.rating||null,listened_at:raw.listenedAt||raw.listened_at||null,discogs_id:raw.id?String(raw.id):null,discogs_type:raw.type||null,cover_url:raw.coverUrl||raw.cover_url||null,genre:raw.genre||null,genres:Array.isArray(raw.genres)?raw.genres:[],styles:Array.isArray(raw.styles)?raw.styles:[],tracklist:Array.isArray(raw.tracklist)?raw.tracklist:[],discogs_url:raw.dgUrl||raw.discogs_url||null,release_year:raw.year?Number(raw.year):null,label:raw.label||null,country:raw.country||null,source_key:key,raw_data:raw};}
async function importDb(){try{const file=$('#dbFile').files[0]; if(!file){log('Choose a file first.');return} log('Reading file...'); const txt=await file.text(); const db=parseDb(txt); if(!db||!db.entries) throw new Error('Could not find VINYL_ARCHIVE_DISCOGS_DB.entries'); details(`DB metadata: version ${db.version}, exportedAt ${db.exportedAt}`); log('Preparing collections...'); const colMap=await ensureCollections(db); const uid=session.user.id; const entries=Object.entries(db.entries); let ok=0, fail=0; for(const [key,e] of entries){const payload=entryToRecord(key,e,uid); const {data,error}=await SB.from('records').upsert(payload,{onConflict:'user_id,artist,album'}).select().single(); if(error){fail++; details(`✗ ${key}: ${error.message}`); continue} ok++; const rawCols=e.collections||e.collectionIds||e.collection_ids||[]; const colIds=[...new Set(rawCols.map(c=>colMap.get(c)).filter(Boolean))]; for(const cid of colIds){await SB.from('record_collections').upsert({user_id:uid,record_id:data.id,collection_id:cid},{onConflict:'record_id,collection_id'});} await SB.from('change_log').insert({user_id:uid,record_id:data.id,action:'import_v4',before_data:null,after_data:payload}); if(ok%25===0) log(`Imported ${ok}/${entries.length}...`);} log(`Import done. ${ok} records imported, ${fail} failed.`);}catch(e){log('Import failed: '+e.message);}}
init();
