-- Dead Wax Supabase Native v1 schema compatibility patch
alter table public.records add column if not exists shelf_id text;
alter table public.records add column if not exists artist text;
alter table public.records add column if not exists album text;
alter table public.records add column if not exists last text;
alter table public.records add column if not exists first text;
alter table public.records add column if not exists copies_owned integer default 1;
alter table public.records add column if not exists note text;
alter table public.records add column if not exists grail boolean default false;
alter table public.records add column if not exists listened boolean default false;
alter table public.records add column if not exists liked boolean default false;
alter table public.records add column if not exists reaction text;
alter table public.records add column if not exists listened_at text;
alter table public.records add column if not exists discogs_id text;
alter table public.records add column if not exists discogs_type text;
alter table public.records add column if not exists cover_url text;
alter table public.records add column if not exists genre text;
alter table public.records add column if not exists genres jsonb default '[]'::jsonb;
alter table public.records add column if not exists styles jsonb default '[]'::jsonb;
alter table public.records add column if not exists tracklist jsonb default '[]'::jsonb;
alter table public.records add column if not exists discogs_url text;
alter table public.records add column if not exists release_year integer;
alter table public.records add column if not exists label text;
alter table public.records add column if not exists country text;
alter table public.records add column if not exists source_key text;
alter table public.records add column if not exists raw_data jsonb default '{}'::jsonb;
alter table public.records add column if not exists updated_at timestamptz default now();
create unique index if not exists records_user_shelf_id_unique on public.records(user_id, shelf_id);
notify pgrst, 'reload schema';
